-- MySQL Script generated by MySQL Workbench
-- Tue Apr  1 11:28:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `iso` INT NOT NULL,
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `iso_UNIQUE` (`iso` ASC) VISIBLE,
  UNIQUE INDEX `idCountry_UNIQUE` (`idCountry` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `idAddress` INT NOT NULL,
  `street` VARCHAR(100) NULL,
  `number` INT NULL,
  `floor` INT NULL,
  `door` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postal_code` INT NULL,
  `country_id` INT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_country_adress_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `idSupplier` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` INT NULL,
  `fax` INT NULL,
  `nif` VARCHAR(15) NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`idSupplier`, `nif`, `address_id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  INDEX `fk_supplier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_supplier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mount_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mount_color` (
  `idmount_color` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmount_color`, `name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`glass_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glass_color` (
  `idglass_color` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idglass_color`, `name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mount_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mount_type` (
  `idmount_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmount_type`, `name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `idGlasses` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `graduation` DECIMAL(2) NOT NULL,
  `price` DECIMAL(2) NOT NULL,
  `supplier_id` INT NOT NULL,
  `mount_color_id` INT NOT NULL,
  `glass_color_id` INT NOT NULL,
  `mount_type_id` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `fk_glasses_supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_glasses_mount_color1_idx` (`mount_color_id` ASC) VISIBLE,
  INDEX `fk_glasses_glass_color1_idx` (`glass_color_id` ASC) VISIBLE,
  INDEX `fk_glasses_mount_type1_idx` (`mount_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses_mount_color1`
    FOREIGN KEY (`mount_color_id`)
    REFERENCES `mydb`.`mount_color` (`idmount_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses_glass_color1`
    FOREIGN KEY (`glass_color_id`)
    REFERENCES `mydb`.`glass_color` (`idglass_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses_mount_type1`
    FOREIGN KEY (`mount_type_id`)
    REFERENCES `mydb`.`mount_type` (`idmount_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `idcustomer` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `postal_code` INT NULL,
  `phone` INT NULL,
  `email` VARCHAR(45) NULL,
  `referredby_id` INT NULL,
  PRIMARY KEY (`idcustomer`),
  CONSTRAINT `fk_customer_referredby_id`
    FOREIGN KEY (`idcustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `idemployee` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `nif` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idemployee`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salesorder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salesorder` (
  `idsalesorder` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `sales_date` DATE NOT NULL,
  PRIMARY KEY (`idsalesorder`, `customer_id`, `employee_id`, `glasses_id`),
  INDEX `fk_customer_customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_glasses_glasses_id_idx` (`glasses_id` ASC) VISIBLE,
  INDEX `fk_employee_employee_id_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_glasses_glasses_id`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `mydb`.`glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
